### ISSUE TITLE
Furnace Upgrade Recipes Require Crusher

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#10]
The Bronze, Iron, and Steel furnaces require a previous tier's Crusher in their recipes, rather than the previous tier's furnace.

Currently, the Bronze Furnace asks for a Stone Crusher (in place of the expected Copper Furnace), and both the Iron and Steel Furnaces ask for a Copper Crusher (in place of the expected Bronze Furnace and Iron Furnace, respectively).

The Copper Furnace does properly ask for a Stone Furnace, however.

**Comment by RebelKeithy** [comment]
Fixed for next update
