### ISSUE TITLE
Dust Issues

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#11]
Iron and Gold dusts cannot be smelted. (looks like the addSmelting() call is skipped in OreInfo because it's behind a !type.equals("RESPAWN") )

Brass dust cannot be crafted - though the MCF thread says it should be copper+zinc, it's currently set to copper+tin, the same as bronze, and bronze appears to claim the recipe.

**Comment by RebelKeithy** [comment]
Fixed for next update
