### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by BSKCraft** [RebelKeithy/Metallurgy3#13]
Just leaving a simple notice that the Stone Crusher has a missing texture while in your inventory and hand. Looks fine when placed. Just started using it but will leave a direct notice on your twitter if I find more missing textures.
![metallurgy 3 missing texture for crusher](https://f.cloud.github.com/assets/3959438/296217/9ffb6f0e-94e6-11e2-80e3-348def9852f2.png)

**Comment by RebelKeithy** [comment]
Unfortunatly,this is a bug with optifine, not metallurgy
