### ISSUE TITLE
[Metallurgy 2.4] Lantern duplicates when placing

### ISSUE THREAD

**Issue by crazz2323** [RebelKeithy/Metallurgy3#16]
[Metallurgy 2.4] Lantern duplicates when placing bug

mcpc-plus-1.4.7-R1.1-SNAPSHOT-f534-244

When I place the lanterns from Metallurgy, the lantern duplicates itself creating another one floating that you can pick up thus duplicating itself. Happens almost every time regardless of the lantern color type. I was referred by the developer to try asking on this site.

I'm using the following Plugins: Catacombs, ExtraHardMode, GravesPlus, InfiniteStrongholds, Likeaboss, McMMO, MobManager, PermissionsBukkit, Realistic Torches, Rebalance Villagers, Spawnmob, WorldEdit, WorldGuard, ZombieRessurrection. 

I am using the following Mods: Ruins 1.4.6, BattleTowers 1.4.6, Metallurgy 2.4 (plus all addon metals), RedPower2.0pr6, (Plus all addons), Industrial Craft 2, and Mo'Creatures.

I am also using Optifine.

**Comment by RebelKeithy** [comment]
This doesn't seem to happen in Metallurgy 3, tested in single player and multiplayer

**Comment by crazz2323** [comment]
If it helps, it seems to happen using the plugin Extra Hard Mode that has a setting for realistic block placement which essentially stops you from placing blocks in the air, while jumping, or on the edge of a surface. I notice if I jump for example, and try to place the lantern it does not place as it shouldn't but then pops a duplicate. The plugin works as it should and I do not have that issue with anything but the lantern. I have not tried Metallurgy 3 with it yet.
