### ISSUE TITLE
Vanilla Hopper Compatibility

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#18]
The vanilla hoppers use their own variant of ISidedInventory (net.minecraft.inventory.ISidedInventory) for determining where to push/pull items.  Currently, hoppers will empty out M3 Furnaces and Crushers entirely (input slot, then fuel slot, then product slot), and will dump items into furnaces (all slots, input/fuel/product) but not crushers.

Cut&paste from the vanilla furnace (TileEntityFurnace into TileEntityMetalFurnace and TileEntityCrusher) seems to work, since they share slot layout and fuel rules (and all three devices are lax about putting arbitrary items in the input slot).  The only other required change is to set the TileEntityCrusher's isStackValidForSlot(int i, ItemStack itemstack) to return true instead of false.

I've tried to tease out what the two ISidedInventory functions do, to get more comfortable with adding them to your codebase.  The first (func_102007_a) seems a simple wrapper for isStackValidForSlot(), but the latter (func_102008_b) is less clear.  It seems related to determining what is a valid extraction target, but I need to play around with it more to be sure.

It seems worth it to add hopper compatibility to these two machines, even if the other two (smelter & abstractor) need to wait for a better understanding of the interface.  On the other hand, that would create an inconsistency in the mod's behavior.

**Comment by RebelKeithy** [comment]
I went ahead an added hopper compatibility for all machines.
