### ISSUE TITLE
Nonfunctional Alloy Dust Recipes

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#19]
Shadow Steel dust, Inolashite dust, Brass dust, and Black Steel dust can't be crafted.

For Shadow Steel and Black Steel, the issue seems to stem from the space in the name of one of the components ("Shadow Iron" and "Deep Iron", respectively).  The appearance of the recipes in CraftGuide supports this.  From the code, the parser expects spaces to be a delimiter between ingredients, so e.g. Black Steel's recipe becomes Infuscolium+Deep+Iron.  The simplist fix here seems to be using some other delimiter character (perhaps '-' or '/') to separate the alloy's components.
(might also remove the quotation marks, which appear entirely superfluous)

Inolashite's entry mispells "Alduorite" as "Adluorite" (transposed 'l' and 'd').

Brass's recipe is identical to Bronze's at present, copper+tin.  In M2, brass used the recipe copper+zinc, keeping them distinct.

**Comment by RebelKeithy** [comment]
Fixed, I just needed to change the delmiter to '" "', I can't believe I didn't already catch that
