### ISSUE TITLE
AIOOBE with new spreadsheet.csv

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#20]
The spreadsheet.csv in Metallurgy.jar from the recent commit ( https://github.com/RebelKeithy/Metallurgy3/commit/f5a1d204891645a16d28cf3ac05e26b359d5fe6d ) adds a new first row.  The parser ( rebelkeithy\mods\metallurgy\core\MetalInfoDatabase.java ) still expects that the first row will be the column headers, and this will be as long as all of the data rows.  However, the new first row is 8 columns shorter than the real header and the data rows, leading to array index out of bounds issues with the initial parsing.

A simple fix would seem to be discarding the first readLine from the spreadsheet.

**Comment by RebelKeithy** [comment]
whoops, I mean to delete the first row before I added it. Having the parser ignore the first row would cause confusion if anyone else tried to use the parser.
