### ISSUE TITLE
Multiplayer Startup Crash

### ISSUE THREAD

**Issue by Wolverine903** [RebelKeithy/Metallurgy3#21]
http://pastebin.com/yZXP2xUT

Still receiving an error upon launching the multiplayer server.  Error log posted in link above.

**Comment by Vyrebird** [comment]
The console log provides a bit more illumination as to cause:

> 2013-03-26 08:44:49 [INFO] [STDOUT] [Metallurgy3] Successfully created/read configuration file for Metallurgy 3 Core
> 2013-03-26 08:44:49 [INFO] [STDOUT] reading sets 1
> 2013-03-26 08:44:49 [INFO] [STDOUT] reading file spreadsheet.csv  from file C:/Users/Keithy/Documents/Metallurgy 3 1.5/eclipse/Metallurgy 3/mods/Metallurgy.jar
> 2013-03-26 08:44:49 [INFO] [STDERR] java.io.FileNotFoundException: C:\Users\Keithy\Documents\Metallurgy 3 1.5\eclipse\Metallurgy 3\mods\Metallurgy.jar (The system cannot find the path specified)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at java.util.zip.ZipFile.open(Native Method)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at java.util.zip.ZipFile.<init>(Unknown Source)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at java.util.zip.ZipFile.<init>(Unknown Source)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at java.util.zip.ZipFile.<init>(Unknown Source)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at rebelkeithy.mods.metallurgy.core.MetalInfoDatabase.readMetalDataFromJar(MetalInfoDatabase.java:148)
> 2013-03-26 08:44:49 [INFO] [STDERR]   at rebelkeithy.mods.metallurgy.metals.MetallurgyMetals.preInit(MetallurgyMetals.java:127)

Maybe forgot to set isRelease to true in rebelkeithy\mods\metallurgy\metals\MetallurgyMetals.java ?

**Comment by RebelKeithy** [comment]
aw crap, I knew I would forget that
