### ISSUE TITLE
Multiplayer Startup Crash

### ISSUE THREAD

**Issue by Wolverine903** [RebelKeithy/Metallurgy3#22]
Still crashing upon start-up. I posted a few logs, not sure if I got the console log that Vyrebird posted last time, I am not sure where or what that is.

http://pastebin.com/tAei3KMS
http://pastebin.com/hN6HSkKZ

**Comment by Wolverine903** [comment]
http://pastebin.com/kWnk28wy

Here is another log that might help.

**Comment by Wolverine903** [comment]
Forge has put a universal/recommended version of it for 1.5.1 just to let you know in case that that might help you figure out the problem.

**Comment by RebelKeithy** [comment]
Again, this particular error is fixed for the next update, hopefully there are no more.
