### ISSUE TITLE
Smelters/Furnaces/Lanterns aren't lighting up

### ISSUE THREAD

**Issue by teh-herper15** [RebelKeithy/Metallurgy3#25]
Smelters, Furnaces, Lanterns, and all machines don't light up when in use. Is this a bug? I am using forge 779.608, optifine HD U B1, backpack mod 1.7.8, and your metallurgy 3.0.0.0.6.1.

**Comment by RebelKeithy** [comment]
lanterns have been fixed for the next update, the other machines never did light up, since light value couldn't depend on the tile entity, I think this has changed, I'll see if I can fix it.

**Comment by teh-herper15** [comment]
Then how does the game make the default furnace light up? I was kind of wondering about that.

**Comment by RebelKeithy** [comment]
it uses 2 separate block ids, one for the idle furnace and one for the burning furnace.

**Comment by RebelKeithy** [comment]
Fixed for next update.
