### ISSUE TITLE
Fantasy Set Config Issues

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#26]
Yes, this is a dupe of https://github.com/RebelKeithy/Metallurgy3/issues/8, but I think I found the cause.

The fantasy config is opened in two places (referenced by their origins in @PreInit, for simplicity's sake):
- MetallurgyMetals.java line 101, which is used for the Machine configuration (ie abstractor)
- MetallurgyMetals.java line 134, as part of the MetalSet constructor (it calls MetalSet.initConfig, which loads and saves the config)

It is likewise saved in two places:
- MetallurgyMetals.java line 134, as part of the MetalSet constructor as mentioned before
- MetallurgyMachines.java line 123, at the end of the initAbstractor method

Now, MetallurgyMetals is the core file for the Metallurgy3Base mod, and MetallurgyMachines is the core file for the Metallurgy3Machines mod, which has a dependency on Metallurgy3Base.  So Metallurgy3Base will always complete its preinit first, which means it will:
1. Open the Fantasy Machine config
2. Open the Fantasy Metal config
3. Close the Fantasy Metal Config
4. Close the Fantasy Machine config

The Fantasy Machine config has no opportunity to load the Fantasy Metal data, and so will always essentially delete it, by overwriting the Fantasy config file with one containing no Fantasy Metal data.

So to fix, either the two configuration files need to get distinct names, or the Fantasy Machine config needs to get loaded _and_ saved either before, or after, the Metal config, rather than spanning across it like now.

**Comment by RebelKeithy** [comment]
Hmm, yes that would be a problem, I shouldn't even be using the fantasy config, abstractor stuff should be in the machines config. Fixed
