### ISSUE TITLE
Machine GUI Not Working

### ISSUE THREAD

**Issue by Wolverine903** [RebelKeithy/Metallurgy3#29]
When you right click on machines to open their GUI, nothing happens.  On the smelters though, it gives a message of Fuel:0 and MaxFuel: 6000.

**Comment by Wolverine903** [comment]
This might help    http://pastebin.com/CUPyCPHU

The first null pointer was from clicking on the crusher, the second one was from the smelter.  But all the machines do not work properly.

**Comment by Wolverine903** [comment]
Same goes for the added chests...they will not open either.

**Comment by RebelKeithy** [comment]
Is this for multiplayer, single player, of both?

**Comment by RebelKeithy** [comment]
Is this for multiplayer, single player, of both?

**Comment by Wolverine903** [comment]
This is for multiplayer..I have not tried single yet.

**Comment by Wolverine903** [comment]
Just for multiplayer, just tried singleplayer and the GUI opens up for each of the machines

**Comment by Wolverine903** [comment]
I don't know if you have the fix for this error yet since you have not wrote much lately, but here is a few more error logs regarding some of the Metallurgy Machines.  And again, these are all are the server only.

EnchantmentTable - http://pastebin.com/QdKuGCRD
Mint Storage - http://pastebin.com/hrtGDu7g
Abstractor - http://pastebin.com/YDsp6CT1

**Comment by RebelKeithy** [comment]
Fixed for next update
