### ISSUE TITLE
Intermittent Crash on Mining or Placement Metablock

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#30]
This error has popped up in some builds but not in others, and I haven't been able to figure out why.  I initially assumed it was a problem with my build process, but it's shown up in some of your official builds too (like the current 3.0.0.0.7.1).

In a build where it does show up, it happens every time I mine a 'metablock' (meta\MetaBlock.java - in essence, the utility ores).  A few times I've tried placing a metablock in those builds (using Creative), and that has crashed me too, though I haven't tested it as much.  On reload of the world, the block is successfully mined (or placed), with the appropriate drops spawned.

>  java.lang.NullPointerException
>   at rebelkeithy.mods.metablock.MetaBlock.func_71934_m(MetaBlock.java:192)
>   at net.minecraft.item.ItemTool.func_77660_a(ItemTool.java:65)
>   at net.minecraft.item.ItemStack.func_77941_a(ItemStack.java:372)
>   at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:169)
>   at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:288)
>   at net.minecraft.client.Minecraft.func_71399_a(Minecraft.java:1241)
>   at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1810)
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:831)
>   at net.minecraft.client.Minecraft.run(Minecraft.java:756)
>   at java.lang.Thread.run(Unknown Source)

My 'fix' is usually just to wrap the subBlocks[meta].getBlockHardness() in a try-catch.  I've tried printing some debug info, but not gotten much of use from it (meta=0, at least).

> public float getBlockHardness(World world, int x, int y, int z)
> {
>    float hardness=0;
>    int meta=-2;
>    try{
>        meta = world.getBlockMetadata(x, y, z);
>        hardness = subBlocks[meta].getBlockHardness();
>    }
>    catch(NullPointerException npe)
>    {
>        npe.printStackTrace();
>    }
>    return hardness;
> }

I have no idea why it happens in some builds, but not in others.

**Comment by RebelKeithy** [comment]
I think it happens when you manage to break the block inbetween it's call to getBlockHardness, I fixed this with a check for null.
