### ISSUE TITLE
Metallurgy Ores Don't Give XP

### ISSUE THREAD

**Issue by Wolverine903** [RebelKeithy/Metallurgy3#33]
This is on the server, have not tested singleplayer, but when ores are smelted in the furnace and then taken out as the ignot, no xp is given or no sound of gaining xp is heard.

Vanilla ores work correctly the way they should though.

Update:  Issue still occurs with new update just so know, and even if you put vanilla ores in the Metallurgy furnaces (i.e. Iron Furnace and I put iron ore in) when the ignots are taken out, no xp is given.

**Comment by RebelKeithy** [comment]
Not a bug, but aww, what the heck. Added for 3.0.0.0.8.1
