### ISSUE TITLE
Inconsistent spawn rates of fantasy ores with default config.

### ISSUE THREAD

**Issue by StanTheMachinegun** [RebelKeithy/Metallurgy3#35]
The spawn rates of certain metals are not respecting the base values in config files (for example Mithril, Oureclase, Rubracium and Astral Silver spawn Very, very rarely when spawn probability is default. plus, they only spawn in very small amounts (1 or 2 blocks), despite having default spawnrate higher than orichalcum (which spawns in excess, and I personally hate it for such abundance) or adamantium. If i modify the spawn rates to say 5 veins per chunk with vein size of 5 (i did set that spawn rate for every metal) I've got (pretty much) even distribution of every metal/ore. I experimented with large quantities of LE TNT for soil and stone removal.

To justify that, I've made "detonation pillars" from bedrock to surface with LE TNT.

Out of 6 such holes i've got only 1 mithril, 1 astral silver, no oureclase, whereas i've got 20+ orichalcum and around 10 adamantium.

**Comment by RebelKeithy** [comment]
I'm looking into it, just so you know there is an easier way to test, there is a debug ore stick that tell you how much of each ore is in a chunk.

**Comment by RebelKeithy** [comment]
this doesn't seem to be happening, I'm going to assume it was got fixed when I updated forge. Test with the OreFinder and reopen if it's still an issue
