### ISSUE TITLE
Emerald, Lapis and Redstone spawnrates are not adjustable.

### ISSUE THREAD

**Issue by StanTheMachinegun** [RebelKeithy/Metallurgy3#36]
There is no option to change Emerald Ore spawning behaviour (there was such option in metallurgy 2). I don't recall being able to set spawn rates of redstone or lapis, but those would be nice features to have (along with ability to change spawnrates of the newly-added Nether Quartz)

**Comment by RebelKeithy** [comment]
Added to the spreadsheet
