### ISSUE TITLE
Metallurgy and Minecraft 1.5.1

### ISSUE THREAD

**Issue by Wolverine903** [RebelKeithy/Metallurgy3#4]
This is more of a compatibility issue than a bug, but I thought I should just put this out here to make you aware.  Minecraft updated to 1.5.1 today and I tried the latest Metallurgy mod you posted last night just to see if it would work and Minecraft just remains at a black screen upon startup.

I used the lastest forge build for Minecraft 1.5.1 and Minecraft loads just fine without the Metallurgy file in the mods folder.

**Comment by Vyrebird** [comment]
I'd spoiler/attach this if I could, but that doesn't seem to be an option here.  

---- Console output snippet ----

> 2013-03-21 16:17:00 [INFO] [ForgeModLoader] Forge Mod Loader has identified 8 mods to load
> 2013-03-21 16:17:00 [INFO] [mcp] Activating mod mcp
> 2013-03-21 16:17:00 [INFO] [FML] Activating mod FML
> 2013-03-21 16:17:00 [INFO] [Forge] Activating mod Forge
> 2013-03-21 16:17:00 [INFO] [Ideas] Activating mod Ideas
> 2013-03-21 16:17:00 [INFO] [Metallurgy3Core] Activating mod Metallurgy3Core
> 2013-03-21 16:17:00 [INFO] [Metallurgy3Machines] Activating mod Metallurgy3Machines
> 2013-03-21 16:17:00 [INFO] [Metallurgy3Base] Activating mod Metallurgy3Base
> 2013-03-21 16:17:00 [INFO] [Metallurgy3Vanilla] Activating mod Metallurgy3Vanilla
> 2013-03-21 16:17:00 [INFO] [STDERR] Exception in thread "Minecraft main thread" java.lang.NoClassDefFoundError: zv
> 2013-03-21 16:17:00 [INFO] [STDERR]   at java.lang.Class.forName0(Native Method)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at java.lang.Class.forName(Unknown Source)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:50)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)

---- FML log snippet ----

> 2013-03-21 16:17:00 [FINEST] [mcp] Sending event FMLConstructionEvent to mod mcp
> 2013-03-21 16:17:00 [FINEST] [mcp] Sent event FMLConstructionEvent to mod mcp
> 2013-03-21 16:17:00 [FINEST] [FML] Sending event FMLConstructionEvent to mod FML
> 2013-03-21 16:17:00 [FINEST] [FML] Sent event FMLConstructionEvent to mod FML
> 2013-03-21 16:17:00 [FINEST] [Forge] Sending event FMLConstructionEvent to mod Forge
> 2013-03-21 16:17:00 [FINEST] [Forge] Sent event FMLConstructionEvent to mod Forge
> 2013-03-21 16:17:00 [FINEST] [Ideas] Sending event FMLConstructionEvent to mod Ideas
> 2013-03-21 16:17:00 [FINE] [ForgeModLoader] Attempting to inject @SidedProxy classes into Ideas
> 2013-03-21 16:17:00 [INFO] [STDERR] Exception in thread "Minecraft main thread" java.lang.NoClassDefFoundError: zv
> 2013-03-21 16:17:00 [INFO] [STDERR]   at java.lang.Class.forName0(Native Method)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at java.lang.Class.forName(Unknown Source)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:50)
> 2013-03-21 16:17:00 [INFO] [STDERR]   at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)

---

For contrast, in 1.5.0, the console output at the crash point is:
2013-03-21 16:20:08 [INFO] [Metallurgy3Core] Activating mod Metallurgy3Core

> 2013-03-21 16:20:08 [INFO] [Metallurgy3Machines] Activating mod Metallurgy3Machines
> 2013-03-21 16:20:08 [INFO] [Metallurgy3Base] Activating mod Metallurgy3Base
> 2013-03-21 16:20:08 [INFO] [Metallurgy3Vanilla] Activating mod Metallurgy3Vanilla
> 2013-03-21 16:20:09 [WARNING] [ForgeModLoader] The mod id Metallurgy3Core attempted to register channels without specifying a packet handler
> 2013-03-21 16:20:09 [WARNING] [ForgeModLoader] The mod id Metallurgy3Base attempted to register channels without specifying a packet handler
> 2013-03-21 16:20:09 [WARNING] [ForgeModLoader] The mod id Metallurgy3Vanilla attempted to register channels without specifying a packet handler

I'd guess FML got less tolerant in between these builds?

**Comment by RebelKeithy** [comment]
Version 3.0.0.0.4 is updated for minecraft 1.5.1
