### ISSUE TITLE
Nether Metals - recipes and spawnrates

### ISSUE THREAD

**Issue by StanTheMachinegun** [RebelKeithy/Metallurgy3#48]
The following recipes containing nether metals are missing:
- shadow iron + ignatius dust = iron dust
- vulcanite bars = blaze rod

Furthermore, neither vulcanite nor ignatius can be used as fuel.

In addition to the above, the default spawnrates seem inconsistent with default config values (shadow iron is much more rare than lemurite, whereas config states the opposite).

**Comment by RebelKeithy** [comment]
Added Recipes, second issue seems to be the same as #35
