### ISSUE TITLE
Instant block breaking

### ISSUE THREAD

**Issue by ghost** [RebelKeithy/Metallurgy3#58]
This bug was already posted in a wrong place, so you might have not read it yet. I give the link: https://github.com/RebelKeithy/Metallurgy/issues/8

This issue is still in Metallurgy 3.0.0.0.9.4.

**Comment by StanTheMachinegun** [comment]
I second that, the issue concerns every decorative or storage block currently in Metallurgy 3.

**Comment by RebelKeithy** [comment]
fixed in next update
