### ISSUE TITLE
Cobblestone Crusher

### ISSUE THREAD

**Issue by Mem4mc** [RebelKeithy/Metallurgy3#6]
Cobblestone and Copper crushers do not process Iron ore.
They will process copper and tin.

Running 3.0.0.0.4 with Forge 603

Mem

**Comment by DragonChef** [comment]
I just tested and It looks like none of the crushers process iron or gold but all the metalurgy ores process

Im using Metalurgy 3.0.0.0.4 with Forge 601 MC 1.5.1

**Comment by Vyrebird** [comment]
To clarify, none of the crushers process iron or gold ores (ie it's not specific to the cobblestone & copper variants).

**Comment by RebelKeithy** [comment]
Fixed for next update
