### ISSUE TITLE
Shadowsteel Armour is still indestructible (and gives no protection).

### ISSUE THREAD

**Issue by StanTheMachinegun** [RebelKeithy/Metallurgy3#61]
Shadowsteel armour does not offer any damage reduction (despite armor bar being almost full) and does not wear at all (item takes no damage).

**Comment by anagran** [comment]
Seems like the same issue with veroxyeres armor.

**Comment by RebelKeithy** [comment]
it seems the spreadsheet didn't get updated. should be fixed in next update
