### ISSUE TITLE
Incomplete Config Files

### ISSUE THREAD

**Issue by SusanCalvinDRP** [RebelKeithy/Metallurgy3#62]
I cannot find the place to disable the mod from performing vanilla ore generation. I dont want the mod to affect vanilla ores. I believe Metallurgy 2 had a section called "ores" in the Core Config and the current Core Config file (3.0.0.0.9.4) does not. 

In addition I cannot find the place to disable MET trading (coins) in the configs either. I dont want the mod to affect trading behaviors. This also used to be in the Core Config I think, but it is no longer there. 

Please advise if I have to edit some other file or wait for an update. Thanks!

;)-Sara

**Comment by KirinDave** [comment]
I'd like to add disabling in general needs to be added. Some dimension mods cause Metallurgy3 to perform unpredictably or crash entirely (e.g., Dimensional Doors) and it'd be nice to just turn that off.

**Comment by RebelKeithy** [comment]
Added in next update
