### ISSUE TITLE
Nether Quartz and Coal Spawn Control

### ISSUE THREAD

**Issue by Lycanite** [RebelKeithy/Metallurgy3#67]
It would be nice to have Nether Quarz control, then I can increase the spawn rates and build a lot of things out of quartz.
Also I saw that Redstone, Emerald and Lapis were added for the next update, but I'm not sure about Coal.

**Comment by RebelKeithy** [comment]
Added in next update, it was supposed to be in the last update, but somehow the spreadsheet didn't update.
