### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by jeandjiss** [RebelKeithy/Metallurgy3#68]
hello.

Ive got black screen with metallurgy 3.0.0.0.9.4.

I have minecraft 1.5.2 , forge build 686 ( the same black screen with 684,685,687,688.)

without metallurgy, my config is good. For example, millenaire mod, rei's minimap and backpack mod works fine.

Hope it will be useful for you. I look forward to playing to the first alpha.

**Comment by RebelKeithy** [comment]
it's not updated for 1.5.2
