### ISSUE TITLE
minecraft worldgen does not respect redstone config file

### ISSUE THREAD

**Issue by theChristopherGS** [RebelKeithy/Metallurgy3#72]
No matter what I set the redstone spawn rates/heights to in the config file, redstone only appears according to vanilla Minecraft rules.

**Comment by RhinoKneel** [comment]
I've noticed this and any of the other recently added configs on vanilla ores don't seem to change things. I've made several test worlds to see if any would show but no matter how many mountains I view I havent sen any lapis, redstone, emeralds etc

**Comment by RebelKeithy** [comment]
Fixed
