### ISSUE TITLE
No Gravel?

### ISSUE THREAD

**Issue by RhinoKneel** [RebelKeithy/Metallurgy3#76]
So I updated to 10.2 and while I noticed the dimension setting error for nether quartz right away, I also noticed all gravel seems to be gone from my world. I'm using a seed I've used before and know where some was but I've looked everywhere and something happened to it. Only other mods I updated shortly after was Forestry and Thermal Expansion which neither made world gen changes from their previous versions.
Anyone else have this problem or could it truly be something else?

**Comment by RhinoKneel** [comment]
I will note though gravel paths at villages still generate, but no where else

**Comment by RebelKeithy** [comment]
fixed
