### ISSUE TITLE
Cannot Configure Fantasy Item IDs

### ISSUE THREAD

**Issue by Vyrebird** [RebelKeithy/Metallurgy3#8]
The Fantasy config file does not include the item ID ranges for the fantasy metal items, so their autoassigned IDs cannot be altered.
(so they just clobber whatever items had those IDs already >< )

Edit - The same appears to be true with several Utility items as well, namely:
Phosphorous
Sulfur
Saltpeter
Magnesium
Bitumen
Potash

(further cases would be easier to spot if NEI worked for 1.5.1)

**Comment by RebelKeithy** [comment]
Hint: if you press f3+h, in vanilla minecraft, it will show item ids.

**Comment by Vyrebird** [comment]
ooo, thanks for that!

As for the configs, it looks like during startup the configs get over-written.  By chance, I caught the Utility config with full options regarding spawning Bitumen ore and such, but it was soon overwritten by the small item-ids config.  So somehow the later writes, which presumably should be appended to the file, are instead overwriting it.

**Comment by RebelKeithy** [comment]
Oh, I misread your issue, there actually is a config option for the metals, under each one is the option "I:"Item IDs (reserves 50)"=18200", the utility items are missing, I'll look into that.

**Comment by RebelKeithy** [comment]
should be fixed.

**Comment by Vyrebird** [comment]
What I mean is that MetallurgyFantasy.cfg is, in its entirety,

> # Configuration file
> 
> ####################
> 
> # abstractor
> 
> ####################
> 
> abstractor {
>     D:"Bonus Admantine"=3.2
>     D:"Bonus Aredrite"=1.8
>     D:"Bonus Atlarus"=3.6
>     D:"Bonus Black Steel"=1.4
>     D:"Bonus Deep Iron"=1.2
>     D:"Bonus Haderoth"=2.4
>     D:"Bonus Mithril"=2.0
>     D:"Bonus Oreichalcum"=2.8
>     D:"Bonus Oureclase"=1.6
>     D:"Bonus Prometheum"=1.0
>     D:"Bonus Tartarite"=4.0
>     I:"Speed Adamantine"=6
>     I:"Speed Aredrite"=14
>     I:"Speed Atlarus"=4
>     I:"Speed Block Steel"=18
>     I:"Speed Deep Iron"=20
>     I:"Speed Haderoth"=10
>     I:"Speed Mithril"=12
>     I:"Speed Orichalcum"=8
>     I:"Speed Oureclase"=16
>     I:"Speed Prometheum"=22
>     I:"Speed Tartarite"=2
> }

There is no config for the metal properties - the ore generation, the tool/armor attributes, the ids for the ore/brick/block/items, etc.  The other metal groups have those options, but the Fantasy ore/metal config appears to be overwritten by the abstractor config info.
